package Spaceship.Operations;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

public class MovableAdapterGeneratorTest {

    @Test
    public void testGenerateAdapter() {
        String result = MovableAdapterGenerator.generateAdapter("TestAdapter", "Spaceship.Operations.IMovable");
        assertNotNull(result);
        assertEquals("AutoGenerated.TestAdapter", result);
    }

    // Дополнительные тесты можно добавить для других сценариев
}
