package Spaceship;

import Spaceship.Operations.*;

public class Main {
    public static void main(String[] args) throws ClassNotFoundException {
        String adapterClassName = "TestAdapter"; // Убедитесь, что здесь правильное имя
        String interfaceName = "Spaceship.Operations.IMovable";

        // Генерация адаптера
        MovableAdapterGenerator.generateAdapter(adapterClassName, interfaceName);

        // Создаем экземпляр UObject
        UObject obj = new UObject();

        // Получаем адаптер через IoC
        Class<?> adapterClass = Class.forName("AutoGenerated." + adapterClassName);
        IMovable adapter = (IMovable) IoC.Resolve("Adapter", adapterClass, obj);

        // Задаем и получаем позицию через адаптер для тестирования
        Vector position = new Vector(5, 10);
        adapter.setPosition(position);
        Vector currentPosition = adapter.getPosition();

        System.out.println("Текущая позиция: " + currentPosition);
    }
}
