package spaceship.operations;

import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;

public class MovableAdapterGenerator {

    public static String generateAdapter(String className, String interfaceName) {
        String adapterTemplate =
                "package AutoGenerated;\n" +
                        "import " + interfaceName + ";\n" +
                        "public class " + className + " implements " + interfaceName + " {\n" +
                        "  UObject obj;\n\n" +
                        "  public " + className + "(UObject obj) {\n" +
                        "      this.obj = obj;\n" +
                        "  }\n\n" +
                        "  public Vector getPosition() {\n" +
                        "      return IoC.Resolve(\"" + interfaceName + ":position.get\", obj);\n" +
                        "  }\n\n" +
                        "  public Vector getVelocity() {\n" +
                        "      return IoC.Resolve(\"" + interfaceName + ":velocity.get\", obj);\n" +
                        "  }\n\n" +
                        "  public void setPosition(Vector newValue) {\n" +
                        "      IoC.Resolve(\"" + interfaceName + ":position.set\", obj, newValue).Execute();\n" +
                        "  }\n" +
                        "}\n";

        // Сохранение сгенерированного кода в файл
        try {
            Path path = Paths.get("src/main/java/AutoGenerated/" + className + ".java");
            Files.createDirectories(path.getParent()); // Создаем директорию если нужно
            Files.writeString(path, adapterTemplate);
        } catch (IOException e) {
            e.printStackTrace();
            return null;
        }
        return "AutoGenerated." + className;
    }
}
