package AutoGenerated;
import Spaceship.Operations.IMovable;
public class TestAdapter implements Spaceship.Operations.IMovable {
  UObject obj;

  public TestAdapter(UObject obj) {
      this.obj = obj;
  }

  public Vector getPosition() {
      return IoC.Resolve("Spaceship.Operations.IMovable:position.get", obj);
  }

  public Vector getVelocity() {
      return IoC.Resolve("Spaceship.Operations.IMovable:velocity.get", obj);
  }

  public void setPosition(Vector newValue) {
      IoC.Resolve("Spaceship.Operations.IMovable:position.set", obj, newValue).Execute();
  }
}
